name: Pogoda Mail

on:
  schedule:
    - cron: "0 22 * * *"  # 00:00 Polska
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    env:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python weather.py
